
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path
import json
# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
import subprocess
from typing import Any
import sys


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("assets")

def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

window = Tk()

def open_home_page():
    window.destroy()  # Close the current window
    subprocess.run(["python", "gui.py"])  # Open the home page


def buy_split(cookies: str):
    return cookies.split("\n")

def save(buy: str, search: str):
    with open(sys.path[0] + "/../config.json", "r") as f:
        config = json.loads(f.read())
    buyc = buy_split(buy)

    config["cookies"]["search_cookie"] = search
    config["cookies"]["buy_cookie"] = buyc
    config = json.dumps(config, indent=4, sort_keys=False)
    with open(sys.path[0] + "/../config.json", "w") as f:
        f.write(config)
    return

class SetDefault:
    def __init__(self):
        with open(sys.path[0] + "/../config.json", "r") as f:
            config = json.loads(f.read())
            self.buy_cookies = config["cookies"]["buy_cookie"]
            self.search_cookie = config["cookies"]["search_cookie"]
    def set(self, buy_cookie, search_cookie):
        buy_cookies = "\n".join(self.buy_cookies)
        buy_cookie.insert(1.0, buy_cookies)
        search_cookie.insert(1.0, self.search_cookie)

window.geometry("512x384")
window.configure(bg = "#132020")


canvas = Canvas(
    window,
    bg = "#132020",
    height = 384,
    width = 512,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_text(
    161.0,
    43.0,
    anchor="nw",
    text="Cookies",
    fill="#FFFFFF",
    font=("Inter", 50 * -1)
)

back_image = PhotoImage(
    file=relative_to_assets("back.png"))
back_button = Button(
    image=back_image,
    borderwidth=0,
    highlightthickness=0,
    command=open_home_page,
    relief="flat"
)
back_button.place(
    x=10.0,
    y=10.0,
    width=136.0,
    height=64.0
)



entry_image = PhotoImage(
    file=relative_to_assets("entry.png"))
search_cookie_bg = canvas.create_image(
    97.0,
    242.0,
    image=entry_image
)
search_cookie = Text(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
search_cookie.place(
    x=33.0,
    y=210.0,
    width=128.0,
    height=62.0
)

canvas.create_text(
    30.0,
    173.0,
    anchor="nw",
    text="Search cookie",
    fill="#FFFFFF",
    font=("Inter", 20 * -1)
)

buy_cookie_bg = canvas.create_image(
    416.0,
    242.0,
    image=entry_image
)
buy_cookie = Text(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
buy_cookie.place(
    x=352.0,
    y=210.0,
    width=128.0,
    height=62.0
)

canvas.create_text(
    339.0,
    173.0,
    anchor="nw",
    text="Buy cookie(one)",
    fill="#FFFFFF",
    font=("Inter", 20 * -1)
)

save_image = PhotoImage(
    file=relative_to_assets("save.png"))
save_button = Button(
    image=save_image,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: save(buy_cookie.get("1.0", "end-1c"), search_cookie.get("1.0", "end-1c")),
    relief="flat"
)
save_button.place(
    x=374.0,
    y=10.0,
    width=128.0,
    height=64.0
)

setter = SetDefault()
setter.set(buy_cookie, search_cookie)

window.resizable(False, False)
window.mainloop()
